### PR TITLE
Rspec test for Enumerable methods

### PR DESCRIPTION
**Pull request by lucianosarno**
We have created RSpec for the enumerable methods written in the 1st Ruby Project.

### CODE REVIEW

**Review by elmejdki — CHANGES_REQUESTED** [review]
# status: require changes :recycle: 
## Great job so far guys :+1: :100: :1st_place_medal:, you have used the coding conventions for tests well done :clap: :clap: :clap:, but you sill have extras work to take care of.

- [ ] you have an error on your spec please fix it:
image

- [ ] I see that you have forgotten to configure GitHub linter please do so.

- [ ] Please Test your methods in different scenarios, with ranges with arrays, with block without a block, with procs, ... etc, and so on, and try also to cover the negative cases.

- [ ] why you didn't use the original repository?. cause now you will need to work on your readme cause it's empty.

### Please make all the required changes before you submit another code review.
## Happy Coding :tophat:

**Review by jubaan — CHANGES_REQUESTED** [review]
# Status: Changes Required :recycle: 

## :wave: :wave: Hello @lucianosarno  and @ggotora  . Thanks for submitting you project!

Great things that the project has:
:100: has a test for each method
:100: all test are passing
:100: RSpec syntax looks good

There are some issues that need to be addressed before we can move forward. Please review the list below.

## Required changes :wrench: 
### [Mandatory] :red_circle: 

- [ ] Issue Link is broken in README file.

- [ ] License Link is broken in README file.

- [ ] Give one line space between ```describe``` blocks and ```it``` statements to improve the readability of the code. 

- [ ] Array string notation should be wrapped around ```[ ]``` square brackets. There are some descriptions and ```it``` statements with this syntax error.

- [ ] ```require_relate``` should be use over ```require``` for repository files.

- [ ] Last line of a ```.rb``` file should be black, swap the last to lines of the ```enum_spec.rb``` file

## Keep up the great work :muscle: and Happy Coding :smiley: :computer:!!

**Review by jubaan — CHANGES_REQUESTED** [review]
# Status: Changes Required :recycle: 

## :wave: :wave: 

There are some issues that need to be addressed before we can move forward. Please review the list below.

## Required changes :wrench: 
### [Mandatory] :red_circle: 

- [ ] The License link takes to a template of an MIT license. Use this information to create the project Licence.

- [ ] Line 19 and 161, need correction for String array notation syntax with ```[ ]``` square brackets.

- [ ] Give one line space between ```it``` statements.

- [ ] Last line of the spec files should be a blank line, swap the comment with the black line.

## Keep up the great work :muscle: and Happy Coding :smiley: :computer:!!

**Review by jubaan — APPROVED** [review]
# :tada: :tada: :tada: :rotating_light: Status: Approved :rotating_light:  :tada: :tada: :tada:

#### :clap: :clap: Great job :hammer_and_pick:!! 

Before submitting add a new line at the end fo the file in the ```enumerable_method``` file

## See you at the top :rocket:!

# :tada: :tada: :tada: :rotating_light: Status: Approved :rotating_light:  :tada: :tada: :tada:

**Pull request merged**
